### ISSUE TITLE
Add documentation?

### ISSUE THREAD

**Issue by gabzim** [SkippyZA/rx-amqplib#2]
Hey, any plans for adding docs for this? Not sure how to implement it in my project.

**Comment by gabzim** [comment]
I've seen the examples but perhaps a README.md?

**Comment by SkippyZA** [comment]
The examples should cover most use cases, but I do have plans to add a proper README. If you have anything specific to ask, make an issue and I will get back to you.

**Comment by SkippyZA** [comment]
@arg20: I have made an update to the README to show where the examples can be found etc. Hope this makes it clearer for the next person to use the library.

Thank you for your input
