### ISSUE TITLE
Missing type definition for Typescript

### ISSUE THREAD

**Issue by UglyDuckling2k** [SkippyZA/rx-amqplib#8]
I don't seem able to find any type definition for Typescript. The library is developed in Typescript so it should be a minor task to generate typings?

**Comment by SkippyZA** [comment]
Thanks for the heads up @UglyDuckling2k I shall look into it

**Comment by SkippyZA** [comment]
Took a little longer than expect, but having the typings included in the dist as part of the build. Hope this is suffice for you.
